
# Name of the pack
name: Golden Signals for Web Servers

# Description of the pack
description: |+
  "## Golden signals alerts for web servers. Includes alerts and a dashboard for\n * throughput\n * errors\n * response time\n * CPU usage\n * memory usage."

# Support level: New Relic | Verified | Community
level: New Relic

# Design
icon: icon.jpeg
logo: logo.png

# Authors of the pack
authors:
  - New Relic
  - Alec Swanson
